# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: shismomanager
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shismo-manager
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shismo-manager

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  region: eu-west-2
  iam:
    role:
      statements: ${file(./.serverless-config/iam-statements.yml)}
  httpApi:
    shouldStartNameWithService: true
    cors: true

params:
  default:
    dynamodbName: shismo-websocket-connections

package:
  individually: true

functions:
  getCharacters:
    handler: handler.getCharacters
    events:
      - httpApi:
          path: /characters/{discordID}
          method: get

  # getUser:
  #   handler: handler.getUser
  #   events:
  #     - httpApi:
  #         path: /user/{discordID}
  #         method: get

  # getCharacter:
  #   handler: handler.getCharacter
  #   events:
  #     - httpApi:
  #         path: /user/{discordID}/{characterName}
  #         method: get

  getTasks:
    handler: handler.getTasks
    events:
      - httpApi:
          path: /tasks/{discordID}/{characterName}
          method: get

  getSkills:
    handler: handler.getSkills
    events:
      - httpApi:
          path: /skills/{discordID}/{characterName}
          method: get

  # setTasks:
  #   handler: handler.setTasks
  #   events:
  #     - httpApi:
  #         path: /tasks/{discordID}/{characterName}
  #         method: put

# resources:
#   Resources:
#     ShismoManagerTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         AttributeDefinitions:
#           - AttributeName: discordID
#             AttributeType: S
#           - AttributeName: characterName
#             AttributeType: S
#         KeySchema:
#           - AttributeName: discordID
#             KeyType: HASH
#           - AttributeName: characterName
#             KeyType: RANGE
#         BillingMode: PAY_PER_REQUEST
#         TableName: shismo-manager

# resources:
#   Resources:
#     ShismoManagerTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         AttributeDefinitions:
#           - AttributeName: discordID
#             AttributeType: S
#           - AttributeName: characterName
#             AttributeType: S
#         KeySchema:
#           - AttributeName: discordID
#             KeyType: HASH
#           - AttributeName: characterName
#             KeyType: RANGE
#         BillingMode: PAY_PER_REQUEST
#         TableName: shismo-websocket-connections
